---
title: Your awesome title
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
  faqs:
    title: FAQs
    output: true
  games:
    title: Games
    output: false
  posts:
    title: Posts
    output: true
  social:
    title: Social Events
    output: true
    date: date
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: authors
  values:
    layout: author
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: social
  values:
    starts at: 
    location name: 
    street address: 
    cost: 
- scope:
    path: ''
    type: games
  values:
    name: 
    start at: 
    is away game: false
    location name: Herring Run Park
    street address: 2254 Chesterfield Ave. Baltimore, MD 21213
