---
title: Your awesome title
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
  games:
    title: Games
    output: false
  posts:
    title: Posts
    output: true
  social:
    title: Social
    output: true
    date: date
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: authors
  values:
    layout: author
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: games
  values:
    event name: 
    starts at: 
    location name: 
    street address: 
    cost: 
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
