---
title: Baltimore Dockers
timezone: EST
collections:
  faqs:
    title: FAQs
    output: true
  games:
    title: Games
    output: false
  posts:
    title: Posts
    output: true
  social:
    title: Social Events
    output: false
    date: date
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: social
  values:
    starts_at: 
    location name: M8 Brewing
    street address: 1399 S Sharp St, Baltimore, MD 21230
    cost: 
- scope:
    path: ''
    type: games
  values:
    name: 
    start at: 
    is away game: false
    location name: Herring Run Park
    street address: 2254 Chesterfield Ave. Baltimore, MD 21213
